config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  has_one_attached :item_image
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }

  def get_item_image(width, height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/shortcake.png')
      item_image.attach(io: File.open(file_path), filename: 'shortcake.png', content_type: 'image/jpeg')
    end
    # item_image.variant(resize_to_limit: [width, height]).processed
    #上のコードだと元ん画像のサイズより大きくできない
    item_image.variant(resize: "#{width}x#{height}!").processed
  end
  
  def with_tax_price
    (price * 1.1).ceil
    # ceilは切り上げ、floorが切り捨て、roundが四捨五入
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_item, only: [:show, :edit, :update]

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def index
    @items = Item.page(params[:page])
    @all_items_count = @items.count
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
  end

  def edit
    @genres = Genre.all
  end

  def update
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :item_image, :price, :is_active)
  end

  def ensure_item
    @item = Item.find(params[:id])
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/items/_index.html.erb
<table class="table mt-3">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %><tr>
      <td><%= item.id %></td>
      <td>
        <%= link_to admin_item_path(item.id) do %>
          <%= item.name %>
        <% end %>
      </td>
      <td><%= number_with_delimiter(item.price) %></td>
      <td><%= item.genre.name %></td>
      <% if item.is_active == true %>
        <td class="text-success font-weight-bold">販売中</td>
      <% else %>
        <td class="text-secondary font-weight-bold">販売停止中</td>
      <% end %>
    </tr><% end %>
  </tbody>
</table>

app/views/admin/items/edit.html.erb
<div class="row">
  <div class="offset-md-1">
    <h5 class="px-4 table-secondary mb-4">商品編集</h5>
  </div>
</div>

<%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>

  <div class="form-group row">
    <label for="inputItemImage" class="col-sm-2 col-form-label">商品画像</label>
    <div class="col-sm-5">
      <%= f.file_field :item_image, accept: "image/*" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label">商品名</label>
    <div class="col-sm-5">
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder: "商品名", class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputIntroduction" class="col-sm-2 col-form-label">商品説明文</label>
    <div class="col-sm-5">
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder: "ここに説明を記述します", class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputGenre" class="col-sm-2 col-form-label">ジャンル</label>
    <div class="col-sm-5">
      <%= f.select :genre_id, @genres.map { |g| [g.name, g.id] }, { include_blank: '-- 選択してください --' }, class:'form-control form-control-sm' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label">税抜価格</label>
    <div class="col-sm-5">
      <%= f.text_field :price, autofocus: true, id:"inputName", placeholder: "1000", class:"form-control" %>
    </div>
    円
  </div>

  <div class="form-group row">
    <label for="inputStatus" class="col-sm-2 col-form-label">販売ステータス</label>
    <div class="col-sm-5">
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_active, true, class: 'form-check-input', checked: (@item.is_active == true) %>
        <%= f.label :is_active, '販売中', value: true, class: 'form-check-label' %>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_active, false, class: 'form-check-input', checked: (@item.is_active == false) %>
        <%= f.label :is_active, '販売停止中', value: false, class: 'form-check-label' %>
      </div>
    </div>
  </div>


<div class="row">
  <%= f.submit '変更を保存', class: "btn btn-success mx-auto" %>
</div>

<% end %>

app/views/admin/items/index.html.erb
<div class="row">
  <div class="offset-1">
    <h5 class="px-4 table-secondary mb-4">商品一覧</h5>
  </div>
  <div class="offset-7"></div>
  <div class="col-md-1">
    <%= link_to '+', new_admin_item_path, class: 'btn btn-light border shadow rounded-circle d-flex justify-content-center align-items-center', style: 'width: 50px; height: 50px; font-size: 30px; color: gray;' %>
  </div>
</div>


<% if @items.first %> <!-- @item.existsと同義、SQL1個分削減(?) -->
	<%= render 'admin/items/index', items: @items %>
	<%= paginate @items %>
<% else %>
	<h3>対応する商品はありませんでした。</h3>
<% end %>

<div class="row justify-content-center">
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="row">
  <div class="offset-md-1">
    <h5 class="px-4 table-secondary mb-4">商品新規登録</h5>
  </div>
</div>

<%= form_with model: @item, url:'/admin/items', class:"mt-3" do |f| %>

  <div class="form-group row">
    <label for="inputItemImage" class="col-sm-2 col-form-label">商品画像</label>
    <div class="col-sm-5">
      <%= f.file_field :item_image, accept: "image/*" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label">商品名</label>
    <div class="col-sm-5">
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder: "商品名", class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputIntroduction" class="col-sm-2 col-form-label">商品説明文</label>
    <div class="col-sm-5">
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder: "ここに説明を記述します", class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputGenre" class="col-sm-2 col-form-label">ジャンル</label>
    <div class="col-sm-5">
      <%= f.select :genre_id, @genres.map { |g| [g.name, g.id] }, { include_blank: '-- 選択してください --' }, class:'form-control form-control-sm' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="inputName" class="col-sm-2 col-form-label">税抜価格</label>
    <div class="col-sm-5">
      <%= f.text_field :price, autofocus: true, id:"inputName", placeholder: "1000", class:"form-control" %>円
    </div>
  </div>

  <div class="form-group row">
    <label for="inputStatus" class="col-sm-2 col-form-label">販売ステータス</label>
    <div class="col-sm-5">
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_active, '販売中', checked: true, class: 'form-check-input' %>
        <%= f.label :is_active, '販売中', value: '販売中', class: 'form-check-label' %>
      </div>
      <div class="form-check form-check-inline">
        <%= f.radio_button :is_active, '販売停止中', class: 'form-check-input' %>
        <%= f.label :is_active, '販売停止中', value: '販売停止中', class: 'form-check-label' %>
      </div>
    </div>
  </div>


  <%= f.submit '新規登録', class: "btn btn-success" %>

<% end %>

app/views/admin/items/show.html.erb
<div class="row">
  <div class="offset-md-1">
    <h5 class="px-4 table-secondary mb-4">商品詳細</h5>
  </div>
</div>

<div class="row mt-3">
  <div class="col-md-4">
    <%= image_tag @item.get_item_image(200,150) %>
  </div>

  <table class="col-md-7">
    <tbody>
      <tr>
        <td class="pb-3">商品名</td>
        <td class="pb-3"><%= @item.name %></td>
      </tr>
      <tr>
        <td class="pb-3">商品説明文</td>
        <td class="pb-3"><%= @item.introduction %></td>
      </tr>
      <tr>
        <td class="pb-3">ジャンル名</td>
        <td class="pb-3"><%= @item.genre.name %></td>
      </tr>
      <tr>
        <td class="pb-3">税込価格<br>(税抜価格)</td>
        <td class="pb-3"><%= number_with_delimiter((@item.price * 1.1).to_i) %>(<%= number_with_delimiter(@item.price) %>)円</td>
      </tr>
      <tr>
        <td>販売ステータス</td>
        <% if @item.is_active == true %>
          <td class="text-success font-weight-bold">販売中</td>
        <% else %>
          <td class="text-secondary font-weight-bold">販売停止中</td>
        <% end %>
      </tr>
    </tbody>
  </table>

</div>

<div class="row mt-5">
  <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success mx-auto" %>
</div>