config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details
  
  validates :post_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :total_payment, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_deposit: 0, confirm_deposit: 1, in_production: 2, preparing_shipment: 3, shipped: 4 }
  
  def get_shipping_informations_from(resource)
    class_name = resource.class.name
    if class_name == 'Customer' # resource: Customer
      self.post_code = resource.post_code
      self.address = resource.address
      self.name = resource.full_name
    elsif class_name == 'Address' # resource: Address
      self.post_code = resource.post_code
      self.address = resource.address
      self.name = resource.name
    end
  end

  def create_order_details(customer)
    unless order_details.first
      cart_items = customer.cart_items.includes(:item)
      cart_items.each do |cart_item|
        item = cart_item.item
        OrderDetail.create!(
          order_id: id,
          item_id: item.id,
          price: item.with_tax_price,
          amount: cart_item.amount
        )
      end
      cart_items.destroy_all
    end
  end
  
  def are_all_details_completed?
    (order_details.completed.count == order_details.count) ? true : false
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_order, only: [:show, :update]

  def index
    if params[:customer_id]
      @customer = Customer.find(params[:customer_id])
      @orders = @customer.orders.page(params[:page]).reverse_order
    elsif params[:created_at] == "today"
      @orders = Order.ordered_today.includes(:customer).page(params[:page]).reverse_order
    else
      @orders = Order.includes(:customer).page(params[:page]).reverse_order
    end
  end

  def show
    @order_details = @order.order_details.includes(:item)
    @customer = @order.customer
  end

  def update
    if @order.update(order_params) && @order.confirm_deposit?
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

  def ensure_order
    @order = Order.find(params[:id])
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="offset-md-1">
    <h5 class="px-4 table-secondary">注文履歴一覧</h5>
  </div>
</div>

<table class="table col-md-12">
  <thead class="bg-light">
    <th>購入日時</th>
    <th>購入者</th>
    <th>注文個数</th>
    <th>注文テータス</th>
  </thead>

  <tbody>
    <% @orders.each do |order| %><tr>
      <td>
        <%= link_to admin_order_path(order.id) do %>
          <%= order.created_at.strftime("%Y/%m/%d　%H:%M:%S") %>
        <% end %>
      </td>
      <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
      <td><%= order.order_details.sum(:amount) %></td>
      <td><%= I18n.t("enums.order.status.#{order.status}") %></td>
    <% end %>
  </tbody>
</table>

<div class="row justify-content-center">
  <%= paginate @orders %>
</div>

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="offset-md-1">
    <h5 class="px-4 table-secondary">注文履歴詳細</h5>
  </div>
</div>

<div class="row">

  <table class="col-md-6 mb-3">
    <tbody>
      <tr>
        <th>購入者</th>
        <td><%= @order.customer.last_name %><%= @order.customer.first_name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.post_code %><%= @order.address %>
          <br><%= @order.name %>
        </td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= I18n.t("enums.order.payment_method.#{@order.payment_method}") %></td>
      </tr>
      <tr>
        <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
          <th>注文ステータス</th>
          <td>
            <%= f.select :status, Order.statuses.keys.map { |s| [I18n.t("enums.order.status.#{s}"), s] }, selected: @order.status %>
            <%= f.submit "更新", class:"btn btn-sm btn-success" %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>

  <table class="table table-bordered border-dark">
    <thead>
        <tr>
          <td class="table-secondary border-dark">商品名</td>
          <td class="table-secondary border-dark">単価(税込）</td>
          <td class="table-secondary border-dark">数量</td>
          <td class="table-secondary border-dark">小計</td>
          <td class="table-secondary border-dark">制作ステータス</td>
        </tr>
      </thead>
    <tbody>
      <% @order_details.each do |detail| %>
        <tr>
          <td class="border-dark"><%= detail.item.name %></td>
          <td class="border-dark"><%= number_with_delimiter((detail.item.price * 1.1).to_i) %></td>
          <td class="border-dark"><%= detail.amount %></td>
          <td class="border-dark"><%= number_with_delimiter(detail.item.price * detail.amount) %></td>
          <td class="border-dark">
            <%= form_with model: detail, url: admin_order_order_detail_path(order_id: @order.id, id: detail.id), method: :patch do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map { |s| [I18n.t("enums.order_detail.making_status.#{s}"), s] }, selected: detail.making_status %>
              <%= f.submit "更新", class:"btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table>
    <tbody>
      <tr>
        <th>商品合計</th>
        <td><%= number_with_delimiter(@order.total_payment - @order.shipping_cost) %></td>
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @order.shipping_cost %></td>
      </tr>
      <tr>
        <th>請求金額合計</th>
        <td><%= number_with_delimiter(@order.total_payment) %></td>
      </tr>
    </tbody>
  </table>
</div>