config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get 'homes/top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about'
    
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7654f8b8fe.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <header class="border border-dark">
      <nav class="navbar navbar-expand-lg navbar-light px-4">
        <%= link_to "LOGO", root_path, class:"btn btn-lg btn-outline-secondary px-5" %>
        <div class="d-flex flex-column mt-3 ml-auto">
          <ul class="row list-unstyled mr-auto">
            <% if admin_signed_in? %>
              <li class="mr-5">
                <%= link_to "商品一覧", admin_items_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "会員一覧", admin_customers_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "注文履歴一覧", admin_orders_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-outline-secondary" %>
              </li>
            <% elsif customer_signed_in? %>
              <li class="mr-5">
                <%= link_to "マイページ", mypage_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "商品一覧", items_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "カート", cart_items_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-outline-secondary" %>
              </li>
            <% else %>
              <li class="mr-5">
                <%= link_to "About", homes_about_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "商品一覧", items_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="mr-5">
                <%= link_to "新規登録", new_customer_registration_path, class:"btn btn-outline-secondary" %>
              </li>
              <li class="">
                <%= link_to "ログイン", new_customer_session_path, class:"btn btn-outline-secondary" %>
              </li>
            <% end %>
          </ul>
          <% if admin_signed_in? %>
            <%= form_tag(admin_search_path, method: :get, class:"form-inline my-1 ml-auto") do %>
              <%= text_field_tag "search[content]", "", :placeholder =>"会員: 姓,名,セイ,メイ / 商品: 商品名", class:"form-control" %>
              <%= select_tag "search[model]", options_for_select({ "会員" => "customer", "商品" => "item" }), class:"form-control" %>
              <%= select_tag "search[method]", options_for_select({ "部分一致" => "partial", "前方一致" => "forward", "後方一致" => "backward", "完全一致" => "perfect" }), class:"form-control" %>
              <%= submit_tag '検索', class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </div>
        </div>
      </nav>
    </header>

    <main class="container-fluid flex-grow-1 border border-dark">
      <div class="mx-5 mt-5 px-5">
        <%= yield %>
      </div>
    </main>

    <footer class="container-fluid border border-dark p-5">
      <div></div>
    </footer>
  </body>
</html>